---
title: "KU Engagement Network"
author: "문기범"
date: '2019 12 18 '
output: 
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
bibliography: library.bib
mainfont: NanumGothic
# csl: apa-5th-edition.csl
number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 연구목적

대학은 학생이 다양한 경험을 할 수 있는 교육적 환경을 제공한다. 학생들은 정규 교과활동 뿐만 아니라 해외교환학생 파견, 동아리 활동, 사회 봉사 등 여러 비교과 활동을 통해 각자의 역량을 개발한다. 학교에서 경험할 수 있는 다양한 활동에 적극적으로 참여하는 것은 학생 성공을 정의하는 하나의 기준이 되기도 한다.  미국이나 유럽에 소재한 명문 대학들은 학생 참여 활동의 중요성을 인지하고 이에 대한 통합적인 관리를 실시하고 있다. 국내에서도 점차 많은 대학들이 교과 및 비교과 활동을 통합 관리하기 위한 시스템을 도입하고 있다. 그러나 아직까지 학생 참여에 대한 객관적이고 정량적인 분석을 실시한 연구는 많지 않은 것으로 보인다. 

여러 연구에서 특정 학생 참여 활동의 특징 및 효과에 대한 분석을 실시 했다. 예시 . 하지만 이러한 연구는 주로 개별적인 활동에 대해서만 분석을 진행했기 때문에, 전체 학교 단위에서 진행되는 학생 참여 활동들을 통합적으로 이해하기에는 부족하다. 과거에는 학생 참여 활동을 체계적으로 분석하기 위한 통합적인 데이터가 매우 제한되어 있었다. 보다 최근에는 빅데이터 분석의 중요성에 대한 인식이 높아지면서 몇몇 대학에서 학생 참여 활동을 통합적으로 관리하기 위한 시스템을 도입하고 있다. 이러한 시스템을 통해 체계적인 학생 참여 분석을 수행하기 위한 빅데이터가 수집될 수 있을 것으로 기대된다. 하지만 상대적으로 학생 참여 활동을 체계적으로 분석하기 위한 분석틀은 충분하게 마련되어 있지 않은 것으로 보인다.

이에 본 연구에서는 생태학적 다양성 지표와 소셜 네트워크 분석을 바탕으로 대학내 학생 참여 활동에 대한 참여 네트워크 모델(engagement network model)을 구축하고자 한다. 참여 네트워크 모델은 각 학생 참여 활동 특징을 분석하고 이를 비교 분석하기 위한 분석틀을 제공할 수 있다. 나아가 최근 급속도로 발달하고 있는 머신러닝 기법을 활용해 학생 참여 활동별 예상 참여 대상 및 그 효과 를 예측하고, 학생별 맞춤 활동을 추천하는 등의 목적으로 활용될 수 있을 것으로 기대된다. 

issdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdf

issdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdf
issdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdfissdf sdfkl sdfsdf issdf sdfkl sdfsdf



[@Clark1997]

@Clark1997 says that 

\begin{equation}
\label{eq-abc}
a + b = c
\end{equation}


